### ISSUE TITLE
\includegraphics[scale=...] no longer works inside overpic environment

### ISSUE THREAD

**Issue by aminophen** [rolfn/overpic#1]
I found a strange difference between the previous version (2010/09/13 v0.53) and the current version (2017/10/06 v1.0). With the current version,

```` tex
\begin{overpic}[<opt-1>]{<img-1>}
  \includegraphics[<opt-2>]{<img-2>}
\end{overpic}
````

when `<opt-1>` does **not** contain `scale=`, it seems that `scale=` in `<opt-2>` is silently ignored. The scaling always worked fine with the previous version.

Here is the MWE:

```` tex
\documentclass{article}
\usepackage{overpic}
\begin{document}

%% scale does not work!
\begin{overpic}[width=.2\textwidth]{golfer.eps}
 \put(90,0){\includegraphics[scale=0.1]{golfer.eps}}
 \put(180,0){\includegraphics[scale=0.01]{golfer.eps}}
\end{overpic}

%% all the codes below works
\begin{overpic}[scale=0.15]{golfer.eps}
 \put(90,0){\includegraphics[scale=0.1]{golfer.eps}}
 \put(180,0){\includegraphics[scale=0.01]{golfer.eps}}
\end{overpic}

\begin{overpic}[scale=0.15]{golfer.eps}
 \put(90,0){\includegraphics[width=.2\textwidth]{golfer.eps}}
 \put(180,0){\includegraphics[width=.1\textwidth]{golfer.eps}}
\end{overpic}

\end{document}
````

**Comment by rolfn** [comment]
Many thanks for your bug report. I hope I found the reason and the last commit (f5949d3) correct it. Please test the new version. I will afterwards make an upload to CTAN.

**Comment by aminophen** [comment]
Hi Rolf,

Thanks for the fix! I downloaded the new one, it works fine. -- hironobu

**Comment by aminophen** [comment]
The new version arrived at CTAN/TeX Live. Thanks!
