### ISSUE TITLE
Add middle coordinate for `\put` 

### ISSUE THREAD

**Issue by econwang** [rolfn/overpic#2]
I want use overpic as a label substitute tool for eps files, a simple parse of original eps file can provide the exact relative position for each label, I am pretty sure the coordinate in eps is located on middle, but in overpic, I think it is left bellow.

Could you please add one more option for the `\put` command that coordinate is located on middle? Thanks!

**Comment by rolfn** [comment]
Hello Stephen,
the `\put` command in `overpic` is the same as in a normal LaTeX picture environment. The reference point is the lower left corner. I'm not willing to change this common used macro. But you can easily define your own put macro. See the following example:
```latex
%---------------------------
\listfiles
\documentclass{article}
\usepackage{overpic,picture}

\newcommand*\cput[3]{\put(#1,#2){\makebox(0,0)[c]{#3}}}

\begin{document}  \Huge

\begin{overpic}[abs,unit=1mm,grid,tics=5,scale=.5]{example-image-a.png}
  \put(0,0){M}
  \cput{10}{30}{M}
\end{overpic}

\end{document}
%---------------------------
```
I hope this helps,

...Rolf
